
name: Build and Release (Linux x86)

on:
  push:
    # Create releases for tags that follow semantic versioning
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Release (Linux x86)
    runs-on: ubuntu-latest # Use a Ubuntu runner, which can target x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # Install any dependencies needed for a basic Rust build for x86 Linux
          sudo apt-get install -y \
            gcc-multilib \
            libx11-dev:i386 \
            libxt-dev:i386 \
            feh # Install feh

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu # Specify the target architecture

      - name: Build (Linux x86)
        run: |
          # Build only for the x86 target
          cargo build --release --target i686-unknown-linux-gnu

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/i686-unknown-linux-gnu/release/fether # Path to your x86 executable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
